available_effects: ["bass"]

randomise_effects: false # If false, applies all the effects in available_effects
min_effects: 1
max_effects: 1

effects:
  - name: bass
    effect_type: bass # Attack and decay times, transfer function points, gain, initial delay, release time
    param_sets:
      - freq_min: 50
        freq_max: 1500
        db_min: 12
        db_max: 22
    weight: 1