transform_type: sox_audio_effect

available_effects: ["eq_18"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
#### TEST
  - name: 'eq_18'
    params: 
      - "equalizer 2001 9 -31"
      - "equalizer 2507 0.7 21"
      - "equalizer 5130 2 -24"
      - "equalizer 7900 2 -26"
      - "equalizer 9000 1 17"
    weight: 1