transform_type: sox_audio_effect

available_effects: ["eq_25"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
#### TEST
  - name: 'eq_25'
    param_sets: 
      - "bass -25 850 1"
      - "treble -25 4000 0.8"
      - "overdrive 15 1"
      - "equalizer 1800 3 15"
      - 'equalizer 2500 2 15'
    weight: 1
