transform_type: sox_audio_effect

available_effects: ["eq_4"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
#### TEST
# 4 Progressive of High cuts with varying q-factor
  - name: 'eq_4'
    param_sets: 
      - "treble -5 1000 0.8"
    weight: 1