transform_type: sox_audio_effect

available_effects: ["equalizer"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
  - name: equalizer
    effect_type: equalizer # Attack and decay times, transfer function points, gain, initial delay, release time
    param_sets:
      - freq_mean: 2000
        freq_std: 700
        db_min: 25
        db_max: 37
    weight: 1