transform_type: sox_audio_effect

available_effects: ["extremely_intense_eq"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1 
max_effects: 1

effects:
#### TEST
# 1 Progressive of High cuts with varying q-factor
  - name: 'extremely_intense_eq'
    param_sets: 
      - "equalizer 8000 1.0 60"  # Extremely aggressive high frequency boost
      - "equalizer 4000 1.5 -45" # Major mid-range notch
      - "equalizer 500 0.8 50"   # Massive low-mid boost
      - "equalizer 100 0.6 -40"  # Severe bass cut
      - "overdrive 40 60"        # Heavy distortion
      - "echo 0.8 0.5 100 0.5"   # Disruptive echo
    gain: 0.04  # Control the intensity of the pink noise
    weight: 1