transform_type: sox_audio_effect

available_effects: ["intense_eq"]
randomise_effects: true # If false, applies all the effects in available_effects

min_effects: 1 
max_effects: 1

effects:
  - name: intense_eq_1
    effect_type: equalizer
    param_sets:
      - freq_min: 100
        freq_max: 120
        gain_min: -35
        gain_max: -30
        q_min: 1.0
        q_max: 1.5
    weight: 1

  - name: intense_eq_2
    effect_type: equalizer
    param_sets:
      - freq_min: 680
        freq_max: 700
        gain_min: -30
        gain_max: -25
        q_min: 1.0
        q_max: 1.5
    weight: 1

  - name: intense_eq_3
    effect_type: equalizer
    param_sets:
      - freq_min: 2000
        freq_max: 2020
        gain_min: 35
        gain_max: 40
        q_min: 1.0
        q_max: 1.5
    weight: 1