# Available SoX effects: https://manpages.ubuntu.com/manpages/lunar/en/man1/sox.1.html#effects
transform_type: sox_audio_effect

available_effects: ["live_recording"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
###### REAL WORLD
  - name: 'live_recording'
    param_sets:
      - "reverb 50 50 100 100" # Reverberation effect simulating a large room
      - "channels 1" # Convert to mono as the model only supports mono audio

external_sounds:  
  - name: pink_noise
    sound_path: 
      - "/mnt/vita/scratch/datasets/audio_effects/sox_noises/pink_noise_10.0s.wav"
    gain: 0.1  # Control the intensity of the pink noise