# Available SoX effects: https://manpages.ubuntu.com/manpages/lunar/en/man1/sox.1.html#effects
transform_type: sox_audio_effect

available_effects: ["lowpass"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
- name: lowpass
  effect_type: lowpass
  param_sets:
    - freq_min: 400
      freq_max: 1000
      weight: 1
