# @package dataset.low_quality_effect.radio_broadcast
mode: set

transform_type: sox_audio_effect

effects:
  - name: 'radio_broadcast'
    params:
      - "bandpass 300 3400" # Typical telephone/radio bandwidth
      - "compand 0.3,1 6:-70,-60,-20 -5 -90 0.2" # Dynamic range compression
      - "gain -n -3" # Slight volume reduction
      - "equalizer 1000 1.5q -2" # Mid-frequency emphasis
      - "channels 1" # Mono output

external_sounds:  
  - name: pink_noise
    sound_path: 
      - "/home/alefevre/datasets/external_sounds/pink_noise/light_pink_noise_60s.wav"
    gain: 0.08  # Control the intensity of the pink noise