transform_type: sox_audio_effect

available_effects: ["equalizer_1", "equalizer_2", "equalizer_3", "lowpass", "highpass"]

randomise_effects: true # If false, applies all the effects in available_effects

# If randomise_effects is true, the number of effects is randomised between min_effects and max_effects
min_effects: 1 
max_effects: 5

effects:
  - name: equalizer_1
    effect_type: equalizer
    param_sets:
      - "equalizer 120 1.0 -30"

  - name: equalizer_2
    effect_type: equalizer
    param_sets:
      - "equalizer 700 1.2 -25"

  
  - name: equalizer_3
    effect_type: equalizer
    param_sets:
      - "equalizer 2000 1.2 30"

  - name: highpass
    effect_type: highpass
    param_sets:
      - "highpass 1500"
  
  - name: lowpass
    effect_type: lowpass
    param_sets:
      - "lowpass 500"
