transform_type: sox_audio_effect

available_effects: ["strong_reverb"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
- name: 'strong_reverb'
  param_sets:
  # Strong reverb: high reverberance (e.g., 70), long HF decay (e.g., 2s), large room scale (e.g., 100), long pre-delay (e.g., 50ms)
  # Pushing reverberation to its absolute limits: zero HF damping, extreme wet gain, and longer pre-delay.
  # Example: reverb [reverberance (0-100)] [hf-damping (0-100)] [room-scale (0-100)] [stereo-depth (0-100)] [pre-delay (ms)] [wet-gain (dB)]
  - "reverb 100 0 100 100 150 9"
  gain: 0.1 # Final gain adjustment for extremely loud and bright reverb with +9dB wet_gain and 0 HF damping
  weight: 1
