transform_type: sox_audio_effect

available_effects: ["medium_compand", "medium_equalizer", "medium_reverb"]
randomise_effects: true # If false, applies all the effects in available_effects

# min and max effects à sélectionner dans available_effects
min_effects: 3
max_effects: 5

# Define a pool of medium-intensity effects for random selection
effects:
  - name: medium_compand
    effect_type: compand # Attack and decay times, transfer function points, gain, initial delay, release time
    param_sets:
      - points_min: "6:-80,-70,-20" 
        points_max: "6:-30,-20,10"
        gain_db_min: -15
        gain_db_max: 5
        attack_s_min: 0.001
        attack_s_max: 0.05
        decay_s_min: 0.02
        decay_s_max: 0.4
        soft_knee_db_min: 0.5
        soft_knee_db_max: 10.0
        initial_delay_s_min: 0.02
        initial_delay_s_max: 0.08
    weight: 1

  - name: medium_equalizer
    effect_type: equalizer # Center frequency, Q factor, gain
    param_sets:
      - freq_hz_min: 50
        freq_hz_max: 15000
        q_factor_min: 0.1
        q_factor_max: 5.0
        gain_db_min: -18
        gain_db_max: 18
    weight: 1

  - name: medium_reverb
    effect_type: reverb # Reverberance, HF damping, room scale, stereo depth, pre-delay, wet gain
    param_sets:
      - reverberance_min: 60
        reverberance_max: 100
        hf_damping_min: 10
        hf_damping_max: 100
        room_scale_min: 60
        room_scale_max: 100
        stereo_depth_min: 30
        stereo_depth_max: 100
        pre_delay_ms_min: 0
        pre_delay_ms_max: 100
        wet_gain_db_min: -3
        wet_gain_db_max: 6
    weight: 1

  - name: medium_lowpass
    effect_type: lowpass # Cutoff frequency
    param_sets:
      - freq_hz_min: 1000
        freq_hz_max: 6000
    weight: 1

# Overall gain to be applied after random effects
gain: 0.5

external_sounds: []