# Available SoX effects: https://manpages.ubuntu.com/manpages/lunar/en/man1/sox.1.html#effects
transform_type: sox_audio_effect

available_effects: ["strong_mp3_compression"]
randomise_effects: false # If false, applies all the effects in available_effects

min_effects: 1
max_effects: 1

effects:
- name: 'strong_mp3_compression'
  param_sets:
  - "lowpass 8000" # Extremely restricted frequency cutoff (telephone quality)
  - "compand 0.001,0.02 15:-90,-70,-30 -15 -90 0.01" # Maximum compression possible
  - "equalizer 1000 1q 8" # Extreme emphasis on mid frequencies
  - "equalizer 4000 2q -10" # Severe cut in upper mids
  - "equalizer 8000 1q -20" # Drastic high frequency attenuation
  - "pitch -60" # Very pronounced pitch artifacts
  - "echo 0.9 0.8 30 0.4" # Strong pre-echo artifacts
  - "bandreject 60 2q" # Filter out some frequencies
  - "dither -s" # Heavy quantization noise
  gain: 0.05
  weight: 1

external_sounds:  
  - name: high_frequency_sine
    sound_path: 
      - "/mnt/vita/scratch/datasets/audio_effects/sox_noises/sine_1000-2000.wav"
    gain: 0.002  # Very low gain value to make the sine wave subtle
