# @package dataset.external_sounds.test_file
mode: set   # list of effects given in parameters, could be mode: random

# Create several modified versions of the HQ audio
# Space separated
# equalizer, freq, Q factor, gain db
# bass gain, freq, q factor
# overdrive, gain db, colour db
transform_type: sox_audio_effect

external_sounds:
  # - name: people_talking
  #   sound_path: 
  #     - "/path/to/people_talking.wav"

  # - name: train_station
  #   sound_path: 
  #     - "/path/to/train_station.wav"
  
  # - name: street_traffic
  #   sound_path: 
  #     - "/path/to/street_traffic.wav"
  
  - name: train_station
    sound_path: 
      - "/mnt/vita/scratch/datasets/external_sounds/test_file.wav"