# @package dataset.low_quality_effect.eq1
mode: set   # list of effects given in parameters, could be mode: random

# Create several modified versions of the HQ audio
# Space separated
# equalizer, freq, Q factor, gain db
# bass gain, freq, q factor
# overdrive, gain db, colour db
transform_type: sox_audio_effect

effects:
#### TEST
# 1 Progressive of High cuts with varying q-factor
  - name: 'eq_1'
    params: 
      - "equalizer 8000 1.0 60"  # Extremely aggressive high frequency boost
      - "equalizer 4000 1.5 -45" # Major mid-range notch
      - "equalizer 500 0.8 50"   # Massive low-mid boost
      - "equalizer 100 0.6 -40"  # Severe bass cut
      - "overdrive 40 60"        # Heavy distortion
      - "echo 0.8 0.5 100 0.5"   # Disruptive echo
    gain: 0.04  # Control the intensity of the pink noise