# @package dataset.low_quality_effect.extreme_mp3_compression
mode: set # Liste des effets spécifiés dans "effects". Peut être random si besoin.

# Available SoX effects: https://manpages.ubuntu.com/manpages/lunar/en/man1/sox.1.html#effects
transform_type: sox_audio_effect

effects:
- name: 'reverb'
  params:
  - "reverb 0.5 0.5 0.5" 
  gain: 0.045 # Niveau de gain équilibré

external_sounds:  
  - name: high_frequency_sine
    sound_path: 
      - "/home/alefevre/datasets/audio_effects/sox_noises/sine_2000Hz_to_2000Hz_10s.wav"
    gain: 0.002  # Very low gain value to make the sine wave subtle
